# Generated by Django 5.2.7 on 2025-10-15 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_author_image'),
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ia_model',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.author'),
        ),
        migrations.AddField(
            model_name='ia_model',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ia_model',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ia_model',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
