# Generated by Django 5.2.7 on 2025-10-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_ia_model_author_ia_model_category_ia_model_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ia_model',
            name='model_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
